/*
const DEBUG = true;
const API_KEY = "AIzaSyBTRdLtPBljKgNWRsPxJsRe9UoZ02QoUW4";
const PROJECT_ID = "galeria-casamiento";
const FOLDER_ID = "1JyB8CK8gBLgJvQy3i8qwkFGHGHvFRCMi";
const UNLIMITED = 999999999;
const CLIENT_ID =
  "821093500667-fasde3gmgsig80ntcja8iqvrrg0jjuh7.apps.googleusercontent.com";
const SERVICE_MAIL = "galeriaapp@galeria-casamiento.iam.gserviceaccount.com";

let photos = [];
let PageToken = null;

async function Authenticate() {
  google.accounts.id.initialize({
    client_id: CLIENT_ID,
    callback: handleCredential,
  });
  google.accounts.id.renderButton(document.getElementById("auth_button"), {
    theme: "outline",
    size: "large",
  });
}

function handleCredential(response) {
  const credential = response.credential;
  if (credential) gapi.load("client", InitializeGapi);
  else console.log("No credentials found", response);
}

async function InitializeGapi() {
  gapi.client
    .init({
      apiKey: API_KEY,
      discoveryDocs: [
        "https://www.googleapis.com/discovery/v1/apis/drive/v3/rest",
      ],
    })
    .then(
      (response) => {
        GetPhotos();
      },
      (err) => {
        console.log(err);
      }
    );
}

async function GetPhotos(pageToken) {
  gapi.client.load("drive", "v3", () => {
    const files = gapi.client.drive.files.list({
      q: `"${FOLDER_ID}" in parents`,
      fields: "*",
      pageToken: pageToken,
    });
    files.execute((response) => {
      // FlipBook(response.files);
      const grid = document.getElementById("grid");
      for (const file of response.files) {
        let video = false;
        if (file.fullFileExtension === "MOV") {
          video = true;
        }

        let grid_item = document.createElement("div");
        grid_item.className = "grid-item";

        let element = null;

        if (!video) {
          element = document.createElement("img");
          element.src = `https://drive.google.com/uc?id=${file.id}`;
        } else {
          element = document.createElement("video");
          element.src = `https://drive.google.com/uc?id=${file.id}`;
          element.autoplay = true;
          element.muted = true;
          element.loop = true;
        }

        grid_item.appendChild(element);
        grid.appendChild(grid_item);
      }

      if (response.nextPageToken) {
        document
          .getElementById("loader")
          ?.setAttribute("class", "loader-enabled");
        PageToken = response.nextPageToken;
      } else {
        document
          .getElementById("loader")
          ?.setAttribute("class", "loader-disabled");
        PageToken = null;
      }
    });
  });
}
*/
const FILES = [
  "https://drive.google.com/uc?id=1hB6B0aEBrff5VQV7wNnbVlm25aRJ3TUVAqV0PlwUqD9Iktap9JTwnJC7",
  "https://drive.google.com/uc?id=1gJDS_UWcaHwLA4sm-cJwYWJimOv6-vVj",
  "https://drive.google.com/uc?id=11dYIpUj88STffHHrttPeGR7QrGbwPmS2",
  "https://drive.google.com/uc?id=17A8s1ZFkJyN5jv54unHisO5zuim4K_qX",
  "https://drive.google.com/uc?id=1LHyksTujFODYlHURghaUBvR2PSvLmAT1",
  "https://drive.google.com/uc?id=1zHxIg1__81wUzR4onf9sPCxE5wDZJ7Ej",
  "https://drive.google.com/uc?id=1a2S2FDxLcqX6ZlmMLjgKh0rsnDaZIV-2",
  "https://drive.google.com/uc?id=1fCDI37-10MYZY13mg7SGL_dSU9ySOv_a",
  "https://drive.google.com/uc?id=1GR9b29HdbezQMP7IbT7Ab1oDswV9Lqd9",
  "https://drive.google.com/uc?id=1qpykKEv3V5aQISY9UcPw976PmzOW4JC7",
  "https://drive.google.com/uc?id=11LWhMJk9xsQGYCcVfn0AzfPnfvhAE1D9",
  "https://drive.google.com/uc?id=17UdZ-8hC_Ru66Gptso-AQznEx8Z-gxKx",
  "https://drive.google.com/uc?id=1oQMH3r_ML2n1XoYTfY9ZmPyihyCCBmTZ",
  "https://drive.google.com/uc?id=1Em8NFsa6AzksjEnRxfhQav9--TZQct1z",
  "https://drive.google.com/uc?id=1MRLurDtEyZ1TadBDCokt295wa3zcAog_",
  "https://drive.google.com/uc?id=14m138KJquXuzgtim_4uv0e0sFsoD3Eul",
  "https://drive.google.com/uc?id=1uMyae1cH0mj4s7heny10X_Dutn1ZtOOQ",
  "https://drive.google.com/uc?id=1ysbXAwyrZbOdFg7Gv_Wb-e-BECIMT0BG",
  "https://drive.google.com/uc?id=1SQdSzkL_xOyDhtgdDyD7_AsT5dUksoPR",
  "https://drive.google.com/uc?id=1-v4FF0r5TaX08TjUMj9e_Gmfdoe0zW1w",
  "https://drive.google.com/uc?id=1JvLbBRoYPJ4RNnoRMtTM5byZLqArrRI3",
  "https://drive.google.com/uc?id=1M8iG6LccdU12BCjF4oZwDfzRRY-NHb12",
  "https://drive.google.com/uc?id=1TtG2Ounlz7buRIcaQ3Fc1f20BvbZZ86U",
  "https://drive.google.com/uc?id=1g2FKr2mOZicvFJ8P62WeqjS3C4vBsb3N",
  "https://drive.google.com/uc?id=1HYrMXx9VdcVzhl5Q_KSMBJjr7C9CKLMT",
  "https://drive.google.com/uc?id=1f5x4oslIBwsNPlEPRiNnElgmcI8MuEeS",
  "https://drive.google.com/uc?id=1E81BEwGB-p09XR5v4wYEc_Q4wUy6YrZ1",
  "https://drive.google.com/uc?id=1-qrPoDyQeFaVwjvoT58w9Pehia3dQBcb",
  "https://drive.google.com/uc?id=18_l7tySl3o9A_Y9TeZKu8tUrWPzcj0sg",
  "https://drive.google.com/uc?id=1vi9WVYb3TfGpswXPwO1NGgqxHve-BpI2",
  "https://drive.google.com/uc?id=1KMX0X7tgTYNZ9npUP6VhelwSTdzZNGzZ",
  "https://drive.google.com/uc?id=1n_XDxujANF53llaQ-CwwIhIUktp23CzS",
  "https://drive.google.com/uc?id=1L0pqWazZAoZz1P6dDOqdpF9-M3QfqyIz",
  "https://drive.google.com/uc?id=1fi0vA8XF4L5uYRcOw6fEUnN_STkX7eIn",
  "https://drive.google.com/uc?id=1wlHnsS4VWVb-uhXy-wCNF6qsKhnnbNE4",
  "https://drive.google.com/uc?id=1diREenv1ellAjtLyG_4AkV2TIzvkKMbN",
  "https://drive.google.com/uc?id=1OL86MFDI2FzP0TW2Hau0et8IGgxRKLuz",
  "https://drive.google.com/uc?id=1tyYdBXLprR8xf-3wbB_TZqVqjyWJR9Qa",
  "https://drive.google.com/uc?id=1ckOokGb6bC0rL4BaEC0TD2_waVGxiIMZ",
  "https://drive.google.com/uc?id=1QshoyKHMk11reVcjjRz_1TPcfLRoORNq",
  "https://drive.google.com/uc?id=1vfBnTRMYdsatPnBuBTLk-GqEzECR2V3q",
  "https://drive.google.com/uc?id=1Lt3kAPww4_ozHDu6vAxwMM2yRQBpgxPD",
  "https://drive.google.com/uc?id=1gG8lWzBiCmrtMv3MONhcy9YQezq-QycY",
  "https://drive.google.com/uc?id=1Npre08JQgUNEz0TwjE7Hiu8iqquDn5ig",
  "https://drive.google.com/uc?id=1gRPBUW7zFp24j6IZWIXMDozBRPyIrz7J",
  "https://drive.google.com/uc?id=1ybny6rr3BA07gd6OJKOxK2BMPujWgYVn",
  "https://drive.google.com/uc?id=1TO9Gx7uVIDE94-8zgFLPgDZw9xjykw4l",
  "https://drive.google.com/uc?id=1Rck-V3NYMfZ1ihnXGNO0ic32x3Gmzt0s",
  "https://drive.google.com/uc?id=151PJznh6gNuNVn46pLQpFEfHmAdJjUST",
  "https://drive.google.com/uc?id=1Jl5kDSB0fl-3RY1wqBnvSw7wkjtT5LgL",
  "https://drive.google.com/uc?id=1BHmTRz5Cq2djRWDqiKE1wXeVFJw1zKRi",
  "https://drive.google.com/uc?id=1vU8GKiK03LRND-uU3f-H7b5WVJuXH10z",
  "https://drive.google.com/uc?id=1eAu_0Y8RqmhDz_cqWrhrOArRIZ47UMVi",
  "https://drive.google.com/uc?id=1Z1XWPZFqZBvliycmTXhYW7BbHSug9q-N",
  "https://drive.google.com/uc?id=16UG0xFj0bl0K8xHmKcTWYTPZyRu4Enxn",
  "https://drive.google.com/uc?id=1vqDKEzneB502cQ1xXs3cTnmhrItrztbi",
  "https://drive.google.com/uc?id=19duoacHiLRLSr1yGR1WfS58Z7_uTbvvw",
  "https://drive.google.com/uc?id=1QgSWFIcVOC_nFUwDmrInBbesoeYmjObH",
  "https://drive.google.com/uc?id=1G6Pg1DWLUGS6S5wgfZ9zxtpPsOQkVuJo",
  "https://drive.google.com/uc?id=1XSXNkjurjaaE-xDVtE5opRHSE0YzkzZa",
  "https://drive.google.com/uc?id=1PVE9Y9Y7t01zDyugh4I0gmInhyHpsW4e",
  "https://drive.google.com/uc?id=1LPisQNCEjMmzxWPTY1auhVKf8X5bscAI",
  "https://drive.google.com/uc?id=1pGSMu_QG9UkOv2teqYeK0rafyPeb8iHu",
  "https://drive.google.com/uc?id=1Cv48PvWIinwybLeoLvsOR08zopQwzuH9",
  "https://drive.google.com/uc?id=16r5G5oAsHDWh-sChcE4FKowL2DW-ej1p",
  "https://drive.google.com/uc?id=19farNQDgkIwY_opXiXwq6VOY8IPyDRVL",
  "https://drive.google.com/uc?id=1VNg6BiGH-J41ihwnjOE-of4I8mnL25uu",
  "https://drive.google.com/uc?id=10ZmzZDCCjPPROoM0bw_LRl9Cq7Xa8Pph",
  "https://drive.google.com/uc?id=1dn0Egi7_gh6b097vdXo-LbWGe0xc0Q-U",
  "https://drive.google.com/uc?id=1XQPVU1lzk-2epfU0z2kqwIjgW0gYo2WJ",
  "https://drive.google.com/uc?id=1DbcmuOIWtToVGNdkJShl_1vH6Wt-nlr_",
  "https://drive.google.com/uc?id=1MS7VHy7UNkiSjppxVPUOpoK7xufx7DN4",
  "https://drive.google.com/uc?id=1o7B8NOwCX1tGfGAlouKXGHdYvHTHPLqj",
  "https://drive.google.com/uc?id=1eJzZq9XWUHOzxUWQ7XdSJLIWXwj_o5On",
  "https://drive.google.com/uc?id=1rc41Gze4YUkeFBfQKnDhxXeSDUGBnQBg",
  "https://drive.google.com/uc?id=1Ol85apV_sIMvqgiDiAYs6c5vxk6oRDCc",
  "https://drive.google.com/uc?id=1MtiqWDT85_UjRT0qv16MYS50V2fO7fZB",
  "https://drive.google.com/uc?id=1iRx5JDtKc0MjsVjxlhnT6JY0hDC-muvr",
  "https://drive.google.com/uc?id=18XzFq34OlnzIHNRnyKBrn5phhlQd9S3G",
  "https://drive.google.com/uc?id=1_yixxDYARw7SbzSPI1r6oarvVUi3hIRA",
  "https://drive.google.com/uc?id=1bNX66GZtnmARtOH2VUE9AjvCvrX8gF-e",
  "https://drive.google.com/uc?id=1XHnwF4MECE-o2IeHsBwSSf-Q5KxVvST1",
  "https://drive.google.com/uc?id=1cuZ2a8JWDULdnVCmGJBPKPGC6SROhPZR",
  "https://drive.google.com/uc?id=1shzPFOwjjJSEG3oJTp_XeKCk_dex86Q4",
  "https://drive.google.com/uc?id=1iNsx3JvPsqKyIkVEt-3UjZs8O9MwrCAQ",
  "https://drive.google.com/uc?id=115VWIKKPO_Lj5PTXRc59Ll9C2Yvlr395",
  "https://drive.google.com/uc?id=1J4iNaPm9-V4BrgUwEAB6htUmZ7lrkFZf",
  "https://drive.google.com/uc?id=1_7Jrg7xXSrDnoKKMiNDWNSmaMytp4QG7",
  "https://drive.google.com/uc?id=1bIMJOqsvzXen_Z9lYTocopvMwecg-xha",
  "https://drive.google.com/uc?id=1NJ4zC7da0Id1TTq3Pu1bSOc-bZZ0uy3_",
  "https://drive.google.com/uc?id=1y4kLNkniBhJ0iYE7IutCL-R_xsEBx_na",
  "https://drive.google.com/uc?id=16JZSur-QnzyrvMa_wipvwdzUpTP_7dGQ",
  "https://drive.google.com/uc?id=10a2L_vFuEsgRoC6cnJQWxeQUNGTLP1oG",
  "https://drive.google.com/uc?id=1_Dg3DeSNBieIrC5aFWqaXXlbuxo5u9Ge",
  "https://drive.google.com/uc?id=1o21N4ypMY0AopCcgbxZBpq7HvAlhw2J8",
  "https://drive.google.com/uc?id=1O4cKT95GlCtAWnHMBBfBLyQ0jsaw6HVt",
  "https://drive.google.com/uc?id=1pralwGKH9ASCPbNrBkqJ3GpA0e40SPxr",
  "https://drive.google.com/uc?id=18L0ev41nhNmw1GsSXc6xxohQEAMMmlx5",
  "https://drive.google.com/uc?id=1rKv7hk1IazHl6YH27QS01Eeywjdcx4jY",
  "https://drive.google.com/uc?id=1trhfODFpUbtPdFalpNWNDy8WObUDl6x6",
  "https://drive.google.com/uc?id=1kKesLlJn2YdG0yQsFd0e-xGR9tiDkD0n",
  "https://drive.google.com/uc?id=1Pnrh1QSUdHZBe0XwxjVny1yDSMoYTwBJ",
  "https://drive.google.com/uc?id=1K_zzfaOCSjgVC6rFrXCsOh27axu1kEIP",
  "https://drive.google.com/uc?id=1GHBE6qDXLz0sL5OohfwVmAZcRKCNSISR",
  "https://drive.google.com/uc?id=16v2J_zaLfWRh9pwpIvZ0PD8CEcnRSH7Q",
  "https://drive.google.com/uc?id=1V7OWMYTqJlRt8R8b-CWuvtOL-ID8AyDy",
  "https://drive.google.com/uc?id=1VlmGwG4dIEV-t4EIoEw4DzCmgCBWPKzO",
  "https://drive.google.com/uc?id=1Xp735wIOm8KVqkdYxHAt3a4AVEAD-0yq",
  "https://drive.google.com/uc?id=1DCuI9FtvB94NybIRPbw8mNAXaALgpC3S",
  "https://drive.google.com/uc?id=1h4BY-IeQIYVwYSeQWQfSywpGtJppa5Si",
  "https://drive.google.com/uc?id=1x4GvJqkdbR4tMvaBJTJJIm6qLssqRE2G",
  "https://drive.google.com/uc?id=1h_f4IHIP8icJA1ld1DgttXf6h_yibqCe",
  "https://drive.google.com/uc?id=1ffK-BKdJYEVpL-YCeIj70U3Kjxvu2RJq",
  "https://drive.google.com/uc?id=1oTL_8HIMQGYcWpjJE1H6SWsHXRiWTAA4",
  "https://drive.google.com/uc?id=1ZLz4XhEyL8C6OUceXf653LK1L8ASaMhA",
  "https://drive.google.com/uc?id=1_qZwF_rXX_EF9Ug8l3IHzPf9v3d0i8Gn",
  "https://drive.google.com/uc?id=1DOh7Qr60YharVwbimXMnMaY64sYiJoe2",
  "https://drive.google.com/uc?id=1WQ-BPfwIv6Ir1ZS7SWSlwq4k9MyEm01b",
  "https://drive.google.com/uc?id=1j323c6j2d4yS6aVe3rn183xLUmha_7op",
  "https://drive.google.com/uc?id=1zLXHicIkgyYzCq4Ocz4R4hz_n0mk2r09",
  "https://drive.google.com/uc?id=1KhyAwD2GgfzVwY7sFBsF9Zviu_Q4Q5Du",
  "https://drive.google.com/uc?id=1W2ny6Xe3lbAD_lWkVUyX1kpX1y510c-9",
  "https://drive.google.com/uc?id=1dyUESjcenMxEZZOoC4N2OU3Z9MCniDcd",
  "https://drive.google.com/uc?id=1KhTLQ9jBHN7TdzPoatTEysd1Rr_gToDH",
  "https://drive.google.com/uc?id=1XXl3Ful0_q0kBEoti_WpbQF7bCMzvBpc",
  "https://drive.google.com/uc?id=1_D64aIifFBNk4r7YPs522zAuI6mZ8f1u",
  "https://drive.google.com/uc?id=13iBa2sD7Q-dL-YgQw08doUDNQ9LKbyoz",
  "https://drive.google.com/uc?id=1t2zQx309pQ2KCf_nsdnEglrDtQTnsxfv",
  "https://drive.google.com/uc?id=1EDs50yn-oBoT4PzM4flDa8EFyK26FJ_z",
  "https://drive.google.com/uc?id=1hktiah0w_5tOYqxVz9SH8eaBfjSgUny5",
  "https://drive.google.com/uc?id=1InAcNIHLGHKwf96ZOJjdf0I5K9yi5i2i",
  "https://drive.google.com/uc?id=1LxnRSAJ1y262o8yH40wCIbQiabsgbEhK",
  "https://drive.google.com/uc?id=1z-rBldyhMoYPL3mfhIaF39y0RrMcz0O_",
  "https://drive.google.com/uc?id=1J2659w4i0fgZJh77bgUfvMVKl4_E75nO",
  "https://drive.google.com/uc?id=1cpkxwVCB0yfT3Sbk7pqfNEgrZGM4c3xs",
  "https://drive.google.com/uc?id=1rLnjsabhQrRz_PZo4Mrj0MJzcLP1GoLx",
  "https://drive.google.com/uc?id=1kNikA02_sWBle8X4Q7dWgqNou3GzavjU",
  "https://drive.google.com/uc?id=1Nz9X1fmt0nXHsuHDbPY2ENaKX0-qpd3E",
  "https://drive.google.com/uc?id=16aOMVO9EoSiizmjxsZDjAEhpT4sUZCZS",
  "https://drive.google.com/uc?id=1lKVyA-huEtrjyE100mudhzu0bbV0wX54",
  "https://drive.google.com/uc?id=18Qgpwlyeq2LPLZqxO7c7E-Whk_KgCYWY",
  "https://drive.google.com/uc?id=1s-SK8p4PWbZcPYf5QzrzJceJoDMUISZg",
  "https://drive.google.com/uc?id=1YEyMLdykU7wvjLwaQk9xUDT-Un8cKbFa",
  "https://drive.google.com/uc?id=1IcGAKyAOswpCkIRz0EpQcbFj8J9UZ8jl",
  "https://drive.google.com/uc?id=1H4obRoqqDcWu0CZNfRf71tGjOqhZkZdu",
  "https://drive.google.com/uc?id=1b0YeoA2_7QCLd96ayePPT1S_HW4sI1wL",
  "https://drive.google.com/uc?id=1OsZpapHVhenQsFFu9c6kbAd1J9OPYhW7",
  "https://drive.google.com/uc?id=1nAqbdu3Hh6OGIko4gC1FcjK3Clq96-kW",
  "https://drive.google.com/uc?id=1of0CM7UyTBTyATiSROszIc-536ZiCCav",
  "https://drive.google.com/uc?id=1buHIbi1qsdCvxUZsYLdc6cKjweNq-Yku",
  "https://drive.google.com/uc?id=11bBJfVo73C_63UYH_KmhBH7aB87eIuOX",
  "https://drive.google.com/uc?id=1SfcNfINsEoZ9Lt6Srjo90QmkTwVq9sY_",
  "https://drive.google.com/uc?id=1twsf2ymg0_ahAMzHsTYURZtIt0sYs6Ok",
  "https://drive.google.com/uc?id=1Jh8HiWAALB5bEnZRHQPN6XPzrwFAFZ02",
  "https://drive.google.com/uc?id=16j3Y7xor3yssVDpVgOlycsIWPjhjB-xX",
  "https://drive.google.com/uc?id=1MkcF9JCpfL4rwzsVeusRhN_i6IlrU5bR",
  "https://drive.google.com/uc?id=1O1lSFHrUzKvoiab3PFoE0GqRX30-Bm_K",
  "https://drive.google.com/uc?id=1pvt3mpoNRgd2i7wtmUVTAiTDlj6e4P4K",
  "https://drive.google.com/uc?id=1dmyjP9p3przPqPzt1z_qZmUf8C-xDAJL",
  "https://drive.google.com/uc?id=1WOBYNbs0POmvLMsp6ESVFyMeC9ah6y5O",
  "https://drive.google.com/uc?id=1kSumlsIvnoxrBhLJv6f2MGerZ1w5jmt0",
  "https://drive.google.com/uc?id=1xwvKSiL0rAhO_Vi6klO65CoL1HfDOg8X",
  "https://drive.google.com/uc?id=1hbZ2R4stNxVUK64U0BHNNNLSTFS_Qg4l",
  "https://drive.google.com/uc?id=14yAg_cp8hOqE0L5orpSZ-hXViEwzsuAJ",
  "https://drive.google.com/uc?id=1ELTWGlnGOZil3vJ4eTb_MV31DZA20wG2",
  "https://drive.google.com/uc?id=1ib7yW6fatWCvJ5k1Q3T43i2_tWo-CMKa",
  "https://drive.google.com/uc?id=1Y4oe7rr0S1sAw9iJN0d-zBxaACva_sLy",
  "https://drive.google.com/uc?id=1sHF43UFxUzjUS91YkpGFpKp2I-BouWp8",
  "https://drive.google.com/uc?id=14xM7XKDkZEnd3mMgzny9Iqsb8wCI-gpo",
  "https://drive.google.com/uc?id=1P07EYE7gjFuhOgdV4UCHKWS5VXBNcNXd",
  "https://drive.google.com/uc?id=1d_O80fUC36GUyvGlKkNKo7O5AnRqPDFa",
  "https://drive.google.com/uc?id=1rCDTrYevRMqgCuhhNvR023UJenrHqbo0",
  "https://drive.google.com/uc?id=1R1T86o8Ixeh3fKE_uU8sVv6ByZemYi2l",
  "https://drive.google.com/uc?id=1rXOvDXiI6BiI83DS4QgzrPgaqYid25v0",
  "https://drive.google.com/uc?id=1tyxWy0RjB4NQs7YV4zSzQW3U3F6ZpTvs",
  "https://drive.google.com/uc?id=1Ju5bWubeDCKEhi-RfCWTlzHYRVlEWfuV",
  "https://drive.google.com/uc?id=1Ef5Ve81cLIMhCUEhlnfbhoWOOYjswxbI",
  "https://drive.google.com/uc?id=1MSaNyKWJhox9WrrPGM0b0AS5f1Ow3VQ7",
  "https://drive.google.com/uc?id=1DPb8PhndYMaY8pUs7OuOiMj0nWuxknNl",
  "https://drive.google.com/uc?id=1J6KrALLtjPg2KXXeI6667ZOl3pN8CL8g",
  "https://drive.google.com/uc?id=1lY9sOiqyYMMc5f4tYNCulkTGl4j6Q5g0",
  "https://drive.google.com/uc?id=1mmsh1ZIjADX0S36D7tCUCfuo73kksWr9",
  "https://drive.google.com/uc?id=1UCDrN8YUNJBWG_gRA9xwr71OVWfmArhX",
  "https://drive.google.com/uc?id=10gLIwSEFN7bWQ8EIX5y4-ak_BS0uvxUO",
  "https://drive.google.com/uc?id=10-8SAuDNJs2LPdhoaIv9WYrgar07JS83",
  "https://drive.google.com/uc?id=1gdq2yOhmzFzS0P98DCVZ384tD7xQA0X4",
  "https://drive.google.com/uc?id=1kaGPsyIKQobouOQSKmAU7r38LfsOTbdL",
  "https://drive.google.com/uc?id=1IJ3zcrJAMOqBWwYE6yMttDFcOXpV-gYL",
  "https://drive.google.com/uc?id=1DZb0by6p0GwAprkXLVdcezgHa5SMdCFl",
  "https://drive.google.com/uc?id=1t4gaHeUA7lwVOQH0piUtjs0BG4QPT3wD",
  "https://drive.google.com/uc?id=18UF3hz2cPnrt3oQ2r972jwy2VJ-bvWxk",
  "https://drive.google.com/uc?id=1RlAVIazKEUh_0MM0BAlu4LrQcErT8PWi",
  "https://drive.google.com/uc?id=1jgK-VQhqVY8uVE-KyoGwaVoV6g9tZOmI",
  "https://drive.google.com/uc?id=1wHVLtHBbT0w5q8jj_HtyPgseiE3Cexed",
  "https://drive.google.com/uc?id=1Wz4l6LoXji59PPk0Euvrwm5ipzqHB-67",
  "https://drive.google.com/uc?id=1BqtsZ7dm3gs3Q7AxR0k1Vxkh5TEsH30e",
  "https://drive.google.com/uc?id=1KcdmkNwD3BnlGfdTZJ2W9LSfD4q_TaFV",
  "https://drive.google.com/uc?id=19UMmnSU3enF6YqAsl3PN0S7K23e3A-vb",
  "https://drive.google.com/uc?id=1tvBLidQJ4M8jo4winOKn6k_AT9jilYWP",
  "https://drive.google.com/uc?id=1m5I-yIbtSZ1zx8IM6etnutq8dlglietP",
  "https://drive.google.com/uc?id=1gaU5xsb6Omdykdpr8obd7BqV8fH-a-Nq",
  "https://drive.google.com/uc?id=1bHVpVg3u-nT3P--XxHANPKE1gRPCFPsn",
  "https://drive.google.com/uc?id=13TjZ8pSrUkYQOIHGWpbZtXEkqYlAOdTJ",
  "https://drive.google.com/uc?id=1lPDRi6oIhis10b-6fokp07jESQTwuTiQ",
  "https://drive.google.com/uc?id=1fwGyXjjhU0l9PS0i8qePneWx2vfv3Y8-",
  "https://drive.google.com/uc?id=1vY8A_Jc93MLX1tij-moylIXSO9lwSBzE",
  "https://drive.google.com/uc?id=1_Ws3vZ9GvbUAP3Q4JHTNCQe8OTLA28Xz",
  "https://drive.google.com/uc?id=1G8F2g6NY4GiQ8YqwM3wI7J8WGA9PceXE",
  "https://drive.google.com/uc?id=1-SWS6jeCGOlAPEpmXd3lFFTExxg3g84S",
  "https://drive.google.com/uc?id=1ExNL-J49r2TmO8-DnDX5U2Duumtd4L2N",
  "https://drive.google.com/uc?id=1l8LylFb3iG88ibQQkVCxsRYF-VePSEif",
  "https://drive.google.com/uc?id=1nYr9RlmX8PUsZzLNGnaOPnniBmGwzeqK",
  "https://drive.google.com/uc?id=1g-wxdeDef3w8Mz812dciBjLntiTNHlec",
  "https://drive.google.com/uc?id=1gJAUy6TPNu5wVTIixMrh38yh4OrMYsxf",
  "https://drive.google.com/uc?id=1k2SSW-CSz_7FyDkLMpsCL-sp9TRjyHoV",
  "https://drive.google.com/uc?id=1Rcb7qMFw3mP7mLymgp2t2qkN4DNKay7o",
  "https://drive.google.com/uc?id=1xR8UubhbjEALOHLUQZMhw-wJt2AA6jTW",
  "https://drive.google.com/uc?id=132za0GI6A_qayOO5zajf777oACSjnRIq",
  "https://drive.google.com/uc?id=1Y85PwMeEKtALcP1t58npjXjYH7achXe8",
  "https://drive.google.com/uc?id=123h6mruFGoGUelXhkTsJMmsfPhaMjx_W",
  "https://drive.google.com/uc?id=1o49ehQZxK7qSQazQ8_IGiHFFp_p4_We-",
  "https://drive.google.com/uc?id=1ekjxwyL5TwVXio7o1EyV0-aXfOADnP8D",
  "https://drive.google.com/uc?id=1s6Rm35QC9bhxpqSeZ9i5_jcKszb6rCll",
  "https://drive.google.com/uc?id=1znmRSbvfkxdLg5oIaiCNPujypam9QXBm",
  "https://drive.google.com/uc?id=1eZGMYxwlae-Go8S2NmaFe4Jdh9kBITim",
  "https://drive.google.com/uc?id=1rgzkxyrF45etjcZrw2pBasTQ_94vay2s",
  "https://drive.google.com/uc?id=1W7gnL0E9XAY5AbwNtkyn0TqxBajvNsIv",
  "https://drive.google.com/uc?id=1uIVTRrxFOl06HFM_hjcWDJUmqQj2QjN4",
  "https://drive.google.com/uc?id=1a9abYrq-NMyQpGGTyevuJIvZ_v2TmrLi",
  "https://drive.google.com/uc?id=1TAdPHuMG05Gx0a9ZKm9rWWhJk_Kyks0E",
  "https://drive.google.com/uc?id=1L49sJstqhSF_bEvgY3EM-qvClhAFoGoS",
  "https://drive.google.com/uc?id=1EhdgeKMJ2CrwH3dE2BCcXNSu26jbG9Ln",
  "https://drive.google.com/uc?id=1BbRh1kZ8A00ncYfDSgrk5tHWNguEMPMY",
  "https://drive.google.com/uc?id=1KDEkIU76ghFK_YOHIX_fBraDG06x09qR",
  "https://drive.google.com/uc?id=1OCekYbOsxZw06ekJopAiYE5u75UHX-cN",
  "https://drive.google.com/uc?id=1OopdxlnyRQwA858VWaUBfMrjowoPKqwa",
  "https://drive.google.com/uc?id=17JA4QXuF79RMX5mEd6DVLCXlNiFVBshu",
  "https://drive.google.com/uc?id=1NL8r9lX1uvREPh9Z2ZuJS0JAvaTOjneb",
  "https://drive.google.com/uc?id=1l27xa9HuOatBdyztVg353zpFD4d68PiO",
  "https://drive.google.com/uc?id=1cKVRE2BolYpMk9XhRemwC1ePv2jd2Tye",
  "https://drive.google.com/uc?id=1lF9Pgwfbpgt8p2iUqCD2wqa2A0ujvGai",
  "https://drive.google.com/uc?id=1SBBMuBN8EE49PUvzjMF7mVFroe9xWhLv",
  "https://drive.google.com/uc?id=1NGdwtpG1HntYsBe3SaiPEMElbcuQd4nt",
  "https://drive.google.com/uc?id=13yCObHFVELJY96lYfEINtq6UFP1ZoR40",
  "https://drive.google.com/uc?id=1HcpQBKQvrZf3GSmaPLAw7GTY92p-FAyk",
  "https://drive.google.com/uc?id=1NKKtFbt6t--znoTBosuf1V_PViangUxw",
  "https://drive.google.com/uc?id=1DE1f97yh4dGpXwFxXNeC_N2TDzWsvQgK",
  "https://drive.google.com/uc?id=16k2u7o-0K5OZ3UuHtwZwLzLXLTDBj_JF",
  "https://drive.google.com/uc?id=1jK5jS8E-UK1krL1z0sMSJJnQ0QM4OggX",
  "https://drive.google.com/uc?id=1rnnQcFJU-MeQl56tKfUIzbu618nWgaM_",
  "https://drive.google.com/uc?id=1NTJtbUMR5OH_hSnKjABhyKzYd2oAC9oG",
  "https://drive.google.com/uc?id=1PXWYTecqa9_w29BRx71_kr6tqnGDQkkZ",
  "https://drive.google.com/uc?id=1EkjWpaaTneZBIjkbr-5x-wRk8kpqcUHL",
  "https://drive.google.com/uc?id=1cgZC7UP2_LmbXvEILKA5UB92qjIxTshQ",
  "https://drive.google.com/uc?id=1RIuqV15mcHxW1wHxkcKRL9W--lq_rLZ_",
  "https://drive.google.com/uc?id=1aNlHnh1k9dxq287NZaQR3jpcSGb22SlP",
  "https://drive.google.com/uc?id=1QaCJ4KfGBSaPKyEgJ2hR1O8huBfpcL_s",
  "https://drive.google.com/uc?id=1qsdq-ab5LKfztwC2neOCgM3W_iX3cd_n",
  "https://drive.google.com/uc?id=1obGHTf8ftSrxRJZEjMq8G-nvva8fo00T",
  "https://drive.google.com/uc?id=19NxXLLVZULGYYZN_s8NYuzIYDqHwgKAT",
  "https://drive.google.com/uc?id=1_iFE55wGRf3NwZY2OlA9xdSpZBnAFxxF",
  "https://drive.google.com/uc?id=1zS_crSZIZCRoEeDCptwgVfojC6Fba8Qn",
  "https://drive.google.com/uc?id=105kyG7-y4LXussuPxgzPpfjcRI3GuVwL",
  "https://drive.google.com/uc?id=1H6xjjWNj21_v7RskqjncYPTDViuiBq8k",
  "https://drive.google.com/uc?id=1crYJ-a7QECaU7IaqZVjceezZH4vuJB04",
  "https://drive.google.com/uc?id=102_rKfDknVOPQqFvOiEtZBebyAB_2Tlo",
  "https://drive.google.com/uc?id=1_7mIEsc5S6hiPi1NRtukej_3hBRVl5N_",
  "https://drive.google.com/uc?id=1xfeYCWPhpa2gtYb0nxzVZIritKEjjnkL",
  "https://drive.google.com/uc?id=1OD6Eoa0Ykid5h8rwT6H9ebuVU_Qd9Iuc",
  "https://drive.google.com/uc?id=10eb4SXBBcjaA1fygb0vFVjs7ihIKc1qC",
  "https://drive.google.com/uc?id=18r1m3pMeaOylN8vCQq8bgkmoDINu2qW3",
  "https://drive.google.com/uc?id=1VOi90Ab-_9gl_06sklYjtCnDn5gdUpq2",
  "https://drive.google.com/uc?id=1cTAhPwmmCrHGJMBgHeKs5fF-8Z3yzTiy",
  "https://drive.google.com/uc?id=19us7lAzCTls4HgpNVUio8qS7HIyjlwrj",
  "https://drive.google.com/uc?id=105GpEo6wUhp5MIDZunsb1eoUjNPY74gE",
  "https://drive.google.com/uc?id=1awr-0-783SkW3bq9H-9DSY4TsSXCkI33",
  "https://drive.google.com/uc?id=1lpScsOAsA7Gpvjcdoh4CoPRlbydGCm-C",
  "https://drive.google.com/uc?id=1X3LLuvfvRIVz9UErrpQIOa8dDWF849ix",
  "https://drive.google.com/uc?id=1qkiWELRYB32CxsYINmg6D-LHnSj9aWQg",
  "https://drive.google.com/uc?id=1thNw1uk_AOi97BnEzxn8Fub0hWIrVOX9",
  "https://drive.google.com/uc?id=1tQ5uvueMLRFMXoAWWFFOPNHHFSodhn6N",
  "https://drive.google.com/uc?id=1bQvZ7wQPprXJT4wkHopEqSJ1Snr4lSFX",
  "https://drive.google.com/uc?id=1gOwKe06kGxDZWcafP2c6397SLrlc2N-6",
  "https://drive.google.com/uc?id=1pO8um0a3CsZHNoDSns5he9WEf861VYGL",
  "https://drive.google.com/uc?id=1PWOiMszkuP9gaOrOX7ykTwMGzVpO1khT",
  "https://drive.google.com/uc?id=1mSXZKKeWY_AJ9wXef8Eswqu5hzZSfAWt",
  "https://drive.google.com/uc?id=1qqqPNewcm95iVRXM_B_jONEGhzgvEVQI",
  "https://drive.google.com/uc?id=1AgWyYKYe2kdUDdCMWyZxayhtuqolEIUj",
  "https://drive.google.com/uc?id=1Bjca99NULyQG_le4ve0NcZwPnyPGHAht",
  "https://drive.google.com/uc?id=1PAt0TZ4l4kJMO_uyu7Hk5i7bUvLu6sSa",
  "https://drive.google.com/uc?id=1KYxCQwWUVLbHdUglHpiI-S3HE-vqnpkV",
  "https://drive.google.com/uc?id=1TRTrfmggX8n_rss0vTOBx4cpYAGypZcf",
  "https://drive.google.com/uc?id=19CfXLpdXQhlBV31bjQUG4w4pjs1PlGGW",
  "https://drive.google.com/uc?id=16saFK8kstvBdkgTbHPp3EyX7UJ1SAiVw",
  "https://drive.google.com/uc?id=1VE-fuAXiTj1llGChZ-Bz5eoPCI6eNngc",
  "https://drive.google.com/uc?id=1ZrueKKzcI7xsb4OCYMEZrV8Xj_qhanWG",
  "https://drive.google.com/uc?id=1BfBtH1nxOur6pYSOf7G-7z5NYZCPzIQU",
  "https://drive.google.com/uc?id=1VGBgsAsDcrS96wLIPcYY0wXEdJFuxk3i",
  "https://drive.google.com/uc?id=1CiWnal9QWaf_VlNUZkImFeTWXaAsi8k8",
  "https://drive.google.com/uc?id=1u9EvKaVaYizKBpw9grZxpdgi2f-2-GjL",
  "https://drive.google.com/uc?id=1aQYxfzxF3b5r6-AkGOAOqYsZ3pE-totr",
  "https://drive.google.com/uc?id=1eNq6p5h17ZCXzCqauZgjI55tyYn6_MqR",
  "https://drive.google.com/uc?id=1rwH1yVmrEV1cYaP75KhTdn30TTr5TGbu",
  "https://drive.google.com/uc?id=112J2dyNEvWuL1gfRRInLt8Uuk1hgzq9V",
  "https://drive.google.com/uc?id=1M9jt6Br_AtxDnl1rlkHHRC9GXYE2gUm-",
  "https://drive.google.com/uc?id=1wrh38jEePHZSxMb5uq1cgR0cMd-zh42h",
  "https://drive.google.com/uc?id=1eWHjMWtC3rljH8PKyzRmn0VYDQ8hZ2fi",
  "https://drive.google.com/uc?id=1KQ7Yq4NFeTkkDp_RYxPaeX7RnE9gOlwh",
  "https://drive.google.com/uc?id=1DvhMlq9F9azHFDW_GDXjHQaSszd42A0R",
  "https://drive.google.com/uc?id=1gwkMV5z3syCkjZH80HMqPxZvyLlpnso3",
  "https://drive.google.com/uc?id=1m6fzIYbBDSEC1qFhVyXpwQYjaGLInz4X",
  "https://drive.google.com/uc?id=1V0xbelTcvQ87td1fCqCcadtphFjGdOkm",
  "https://drive.google.com/uc?id=1E7qSyqhdscysBZgFJZbWSI2CApGk1nnq",
  "https://drive.google.com/uc?id=1Wp5C0TYtNR4Jg8r-IycRzAks7YizMUiG",
  "https://drive.google.com/uc?id=1bj8SvXtf0Xf2DxUc38FRKYB3T5dNXWnQ",
  "https://drive.google.com/uc?id=1pGb3gGFAnk1YTDW4vHsWtAY6GZW1WKmp",
  "https://drive.google.com/uc?id=11PzfXoDJGVy3DHMo6IWkZ7tO44zQNYim",
  "https://drive.google.com/uc?id=1pYONGFz1qaPe1Rf1-chNP9-wFrzs0AG4",
  "https://drive.google.com/uc?id=1m-4K3OkSYib123-0wlS_TSGJ8z1LwGfx",
  "https://drive.google.com/uc?id=1_vYmcWXPLriOJVu_WV3Gx_lqsGkKk3Kt",
  "https://drive.google.com/uc?id=1UMdARkYC5Hz7q9WzyOZ7ShM1I3DXKcgM",
  "https://drive.google.com/uc?id=1bTB1BqaJC6s3l1csfDRpKh7TaXNffA26",
  "https://drive.google.com/uc?id=1aUjs2JQMF-orpaOaZUK74KRZvqDbxVVa",
  "https://drive.google.com/uc?id=1RyaAYhpn6-15l-BXgZTeacGf32WN-BCT",
  "https://drive.google.com/uc?id=1DGb2lpC8ZdZiGpRQv5e0m2Hf5yoRCHXH",
  "https://drive.google.com/uc?id=1cVaMIwnT2vzlPfgDiQ3dHSRWKDhRQaF-",
  "https://drive.google.com/uc?id=1y6RHm9C36B1_OMYVigmzT1IJL5JftvhW",
  "https://drive.google.com/uc?id=1j8itVUdRJbkOT9MqtY12EPDVOUhMy7mf",
  "https://drive.google.com/uc?id=10Pt4wAJTr6A72lp94fUoIAJZHTvhDsJ7",
  "https://drive.google.com/uc?id=10aa_C2J-FepI7mXVKGAmls0Odq8sIXpR",
  "https://drive.google.com/uc?id=1qT6olvIvh4lIHGjvirassuqXWzI-_tCC",
  "https://drive.google.com/uc?id=1RDrNcDWJLQB3H7QXi2Kqm6G_TyKWE8AT",
  "https://drive.google.com/uc?id=15zQSMgCgZbzYVDSI1c18gxcIHJo5yDgz",
  "https://drive.google.com/uc?id=1bjJHfX6vlhEgabT0-HOdsYgLauzPebpZ",
  "https://drive.google.com/uc?id=12CoicWlop18gzloILqX_AFvPUdtIl3Fg",
  "https://drive.google.com/uc?id=1JgINODwkZ-y_Eox74-Ez04Bh6u75euF_",
  "https://drive.google.com/uc?id=1FRXWDYETt4qSI1I4B4jawMzcr2jioV6-",
  "https://drive.google.com/uc?id=17rTvnfLbbFDloj8JhS1SvNht7uLKSY3d",
  "https://drive.google.com/uc?id=1cCH8zmU5CmgT9c0QyKmmas4YwGRAWvCQ",
  "https://drive.google.com/uc?id=1ntTG8lN-oK8oJqSseu9o0xf5WsHIECvi",
  "https://drive.google.com/uc?id=1kSh1hj5hiG2H1AH0OTHGZkAdwT9wyTI6",
  "https://drive.google.com/uc?id=1s-d3g2ox2qqu2rSaRIUBJvtweYJtToRc",
  "https://drive.google.com/uc?id=1gE6vMUR-jWechaOGzRAquOSQZ2fW-zI-",
  "https://drive.google.com/uc?id=1oTJUq6bQsA68Cbg1Z-1tVPo2NumZYPgx",
  "https://drive.google.com/uc?id=1QtYuqFJzInbl39E_xpxbpJYSUBeNFwuO",
  "https://drive.google.com/uc?id=1-W0k7jZhS0fMDyjoPZcbAJUL5MVIKU9Y",
  "https://drive.google.com/uc?id=1Uac2CRyz5-dSbEG0PI37MDJOikps6jk_",
  "https://drive.google.com/uc?id=1AixhOtjSHHWthwP7DpnL638Qzq266q7U",
  "https://drive.google.com/uc?id=1y4a2i3UWjBoJHle8ICL1dzZbhvL-wQ3r",
  "https://drive.google.com/uc?id=1WE-ovXlCcwBiqqC8nzXmA2ikh3udoHZ_",
  "https://drive.google.com/uc?id=1NtnujQ1FALwKAfwV9L8OhmpC2l7FznGO",
  "https://drive.google.com/uc?id=1reCC8Ty8xdFMCWWSf56W_MUVgOTed6so",
  "https://drive.google.com/uc?id=1tm35pS2Fw4lYARrPXRrYXAdrMltBZwhI",
  "https://drive.google.com/uc?id=1H8BeohrlhAY464Dvt7EiUDYVL4pfa-5s",
  "https://drive.google.com/uc?id=1vYhab7_5RgYwluLYxBHstF2SIkVDQAJB",
  "https://drive.google.com/uc?id=1pc00RMV2-MxpVoEeJeNVuTHBv2Z7pHxn",
  "https://drive.google.com/uc?id=1VgDQZZTIWj9cfjhGthTmhIGC7GqRBuFx",
  "https://drive.google.com/uc?id=1VdwpK0hupLJwksmDSczJ_WyAfeC4G-dN",
  "https://drive.google.com/uc?id=1JSFJJ3Hsz7nboSp9lgNikX1HXQMv6EAg",
  "https://drive.google.com/uc?id=1vvXiPC2YP4Hs51aK9YwKIwPM-fvK4gs-",
  "https://drive.google.com/uc?id=1FQfUVU7j5erZSvYWAWh-Vgml0tr0yAQ1",
  "https://drive.google.com/uc?id=1h_aFFJqbqU9B2z1xUlIPQkRYq8KOv9VH",
  "https://drive.google.com/uc?id=1y5SZIhhTXWSDIWnx-kqLnhj-YoQrYW3r",
  "https://drive.google.com/uc?id=1UNKQRm3dEaJtDfgP5-pO89L_OF-ZSU3k",
  "https://drive.google.com/uc?id=1SnPeFjQYk4nvovcW7kf4jQoMt6feEr27",
  "https://drive.google.com/uc?id=1bqJ4ohsRhDIfw5nQnOgJjNKHvQETL2gy",
  "https://drive.google.com/uc?id=1MSmxaM621U_7cWJXUFMQ-sRqKbeev-1G",
  "https://drive.google.com/uc?id=1gQG9HmsUy3Bbp2yUt7qS94t19eEJzpvc",
  "https://drive.google.com/uc?id=1-PI6UolGiTLNEBBQ7qGum1wVkv5KRLPi",
  "https://drive.google.com/uc?id=1ETC0iO22MYBmRdB_eZc_LXYgvCYCjxO8",
  "https://drive.google.com/uc?id=1y1-Ogo0B41mvzm6Cyz6iLsWT2BRHDggO",
  "https://drive.google.com/uc?id=1JeoTi7Yud_9PLV0157bNNTnfgRnmikea",
  "https://drive.google.com/uc?id=1KCloO4jBKffJ24NizWzN6XGsaSoZEu70",
  "https://drive.google.com/uc?id=1bumRab6hE9k_VyVkcG0d8jZPpCIMKpAr",
  "https://drive.google.com/uc?id=1iJ9QXUvEgBNUwQl9SSdbtlLbmP83i2Yd",
  "https://drive.google.com/uc?id=1p-sXBqr3cWeVTJX66LBD_5UMaWb6MYKN",
  "https://drive.google.com/uc?id=1VcufxRSlcvoJd7XKsnDNBuEokZln7vKl",
  "https://drive.google.com/uc?id=1sz6dUthTthRzJ6veXk7v5nMUGM-tTywE",
  "https://drive.google.com/uc?id=10DzHMpfcImfiLEH1eTBchk-zgYjJ_I1a",
  "https://drive.google.com/uc?id=1muVfNTOdMN3sa80fQfYGxXpc8-LKeJdD",
  "https://drive.google.com/uc?id=1KZZxfs4KHsAyoe6UNe34dJYFdy-AEMxJ",
  "https://drive.google.com/uc?id=12f0YiUhU8MLKiiUyCEGir4XCLEMKAWDp",
  "https://drive.google.com/uc?id=1K3yfBhF5lZDMsNQKap5xl2-ZUE8Z9KDr",
  "https://drive.google.com/uc?id=1-8xSjSAE6PISdi3rAUFUofJ76iabB9uM",
  "https://drive.google.com/uc?id=1sEIO3n7rZ9apcmWR1VlHbfS8ViMjR1R6",
  "https://drive.google.com/uc?id=1OekuWRyyw9QsBmXiV-C6slHfhUG3c9nU",
  "https://drive.google.com/uc?id=1KgJoJVf3rWp874C70DdajEXsiKJS3GTO",
  "https://drive.google.com/uc?id=1rSTN373PEnyHXiNNu-QX7XNi3Z300jxl",
  "https://drive.google.com/uc?id=1wk7x_MhT2PtEF83z7qncSuAlUyFheJbV",
  "https://drive.google.com/uc?id=1slFa9JVjKx6WnzD3MzALREVum9XhhKXG",
  "https://drive.google.com/uc?id=1R9ZNthbq-8ZowIk4WzqbO15lPs11Bw1_",
  "https://drive.google.com/uc?id=1m_SppnDqJlT94459jQ8RoHljbC0bpTja",
  "https://drive.google.com/uc?id=1wee89mHKf5K0V-W6mDC-tCWkfzipuCQG",
  "https://drive.google.com/uc?id=1QUd5U4QsN1QThLbvtGMSNwLb1HXM9eWW",
  "https://drive.google.com/uc?id=1wnU2HnRzT81O-26nnB2U6zQpNxG5Gzmk",
  "https://drive.google.com/uc?id=1DX-0LOYwE3BnujZp0st-SrikkekHnhFn",
  "https://drive.google.com/uc?id=16BVXAARSiBFF-zJbRNaRqfNnPeNcYCMZ",
  "https://drive.google.com/uc?id=19jn9EmmQsfR3K7252y0jqOVm8tnNVS8L",
  "https://drive.google.com/uc?id=15s8JSHe3EqS0Xgq29Qip-9noWRnLWnX0",
  "https://drive.google.com/uc?id=1aojvnBtJxlS959dSCu_O3gu_DEPnkdts",
  "https://drive.google.com/uc?id=1kPpuGu041DUVtlPpC0wZAxlr69rid6Ar",
  "https://drive.google.com/uc?id=12aNDTQ_2pKUfYkcnOjsGX5Y7niV4TDF1",
  "https://drive.google.com/uc?id=1st1AM4-EMy-_YzerB5fbf-AnYBsyK-N1",
  "https://drive.google.com/uc?id=1IZArZTURoseEutzdGTqU5wI-s4VpKp4_",
  "https://drive.google.com/uc?id=1Eh9X5yiQBWx19f_WFl9-aIHsl6VH8VDe",
  "https://drive.google.com/uc?id=1LasBYIEOEIuyYg6qYKjohGDoNuMYH50l",
  "https://drive.google.com/uc?id=1VUjnCaTnpzbeiFLdrBnrN_ltEAT-aWQ0",
  "https://drive.google.com/uc?id=1k1oxJtkq99Rd4KJM3fd6wLVEx_6o_eHH",
  "https://drive.google.com/uc?id=1ETKW03Hs9gtSSCuJeGWapVXxUhzHx4Ig",
  "https://drive.google.com/uc?id=1yjsBi9oF1TsOwM4HgriUsPer0tRr4T-c",
  "https://drive.google.com/uc?id=1_ZeNSC2Pfg3E5U9UrlNPqSBdF4r7lXzX",
  "https://drive.google.com/uc?id=1Is1afYecJkKfjmn8Zk41F7wAi1mwhL5p",
  "https://drive.google.com/uc?id=1xBrIG2m5DkWivws7K4pj3KWnPirlmuX7",
  "https://drive.google.com/uc?id=1ntswOqJAcqAEMMDxK5-gaEmE7Uj178Yy",
  "https://drive.google.com/uc?id=16jT9E546YZqq58JwynF5lmSz8T0g9OcF",
  "https://drive.google.com/uc?id=1Bv5ExGx5TiQCDDUjnFkTrSZus01hDNcU",
  "https://drive.google.com/uc?id=10xxPc5UHT5VVQv3kjJxE_g8H57vSdzr9",
  "https://drive.google.com/uc?id=1ZhENXFIPBChCcz_kQwbsJkxS98oT5Yiz",
  "https://drive.google.com/uc?id=1iKxieMTaLXBuuJfkkI2dkSTcp3wFaELx",
  "https://drive.google.com/uc?id=17sovrojczw_z4wwVv1xW6D9iiqHNKNsW",
  "https://drive.google.com/uc?id=1cUzlckRM_wZbTpU6w_cjwKVIScGyLehq",
  "https://drive.google.com/uc?id=1QlRMqma29qCeS9aVlWbPda0jQQa6n0es",
  "https://drive.google.com/uc?id=1SviG_bhxXxQjgZqwMjgvsZtCDJEcZt5X",
  "https://drive.google.com/uc?id=11nxyTPpPqHMSeuDArjODiiQeBR9gd4WL",
  "https://drive.google.com/uc?id=1g7-CxlwARrr_NJrL0h1hj4ODjW5016hu",
  "https://drive.google.com/uc?id=16WcEUh8BSEkXtFqbxGj3M0O3ICq-c0kg",
  "https://drive.google.com/uc?id=1Hsqiqu8BAydqxent0ZtjG7hDdnk8niCf",
  "https://drive.google.com/uc?id=1LTWgDpwAXXhWBC9tQMgIRZXhxtPnYUR2",
  "https://drive.google.com/uc?id=16Za61YdTjqFcyQ4ECJfSOv6OjZoPe12t",
  "https://drive.google.com/uc?id=19ouNhWu7oOl_3js3gMjfgkEEQt6SsKsf",
  "https://drive.google.com/uc?id=1UfrE5kne42h92XKGgkkEVeAQyvdSqtc8",
  "https://drive.google.com/uc?id=1x7vKhEYdUooYaZ3fPmhqmUAOCR4kl4Wj",
  "https://drive.google.com/uc?id=12goSCWmvUqq9mHY93y-lk-8WNlVJPkQF",
  "https://drive.google.com/uc?id=1YPK164-XRLgtc4J0-7ayZt1vnjVRtPcD",
  "https://drive.google.com/uc?id=15usA50fMAGYo4tkvPJiqvcwp4zymqQnU",
  "https://drive.google.com/uc?id=1pM2elckowbTuA0dHciaY5STvMiEueAQc",
  "https://drive.google.com/uc?id=1Ue8KANT8XWpiDHRF6CV4vdUB6qhVbLT9",
  "https://drive.google.com/uc?id=1aPG0Rznm1LQFgC_8kipJkkii381KSlK4",
  "https://drive.google.com/uc?id=1g9N0d8vjeD34EKtcxgRv6W6qNr1HJ5C7",
  "https://drive.google.com/uc?id=1PMUrkFX6iCP87VHLphDOXyLO_c7cyZwd",
  "https://drive.google.com/uc?id=1hCKa2SjYaG2SAXWVLpsgbrKfKl-VEg0u",
  "https://drive.google.com/uc?id=1VKG_trDatoweQR1KHmi54wgyUD7irhW4",
  "https://drive.google.com/uc?id=1d6CexLkE5VbLQS-kL0AaBnqYG6OArs1b",
  "https://drive.google.com/uc?id=1z1C4NJf2SHwsSWB6j5-egESxHvxp_7Zc",
  "https://drive.google.com/uc?id=1ZEYmrxFiyNkpz1Ozq2MqlKn8X5PHAtxi",
  "https://drive.google.com/uc?id=1jfWxUUucvy5eT_MaNlKJbfW-w_5oCcdz",
  "https://drive.google.com/uc?id=1wIUu0Hwu2cJBHa1Rj_opBjnTsOIl-OCA",
  "https://drive.google.com/uc?id=1L8kc7OKFUuJGf3y0-HQGkMklkXaDyayA",
  "https://drive.google.com/uc?id=1JwMOwAknajpEZi1djj1fY0q--Q6wsski",
  "https://drive.google.com/uc?id=171z0x4YzftHraMpaa0aakzz-pQAKaR5g",
  "https://drive.google.com/uc?id=1UGhLb-1aBA09-vTc8Dr39t2OtsGosS8V",
  "https://drive.google.com/uc?id=1wwe7K2aW0ipw4O4srmB_VxF8AllmPfgx",
  "https://drive.google.com/uc?id=1dDNCJC64ckJZUCzjhJG1eOhG2PyYbTKq",
  "https://drive.google.com/uc?id=1l9NOvEDlplsUUs2wF8O_h-9YqONIp2YZ",
  "https://drive.google.com/uc?id=14G0M21JUC9Zd0I6mILkCaMHnxdL8xvpg",
  "https://drive.google.com/uc?id=1ozSrfQzbfkClmi7zyS7pFJ270YrbLDJk",
  "https://drive.google.com/uc?id=1D-wyi3BwH8ZzUKoyfPnJlbsPXAroJsSB",
  "https://drive.google.com/uc?id=1hWmciFUMAuPlTnJSaO9mCacXV217tsuh",
  "https://drive.google.com/uc?id=1g4a745WxXfE76Xs6RUD_q9KV_4Yr6ue-",
  "https://drive.google.com/uc?id=1NM--8kRkwZlUtxh7gV6avG98maJFeLTg",
  "https://drive.google.com/uc?id=1j2_67sJBgYswS7MytB_BjnzXoeGUgXnv",
  "https://drive.google.com/uc?id=1rDZ5eE6ZDiJfokzAicx9HqaMmp3FenE9",
  "https://drive.google.com/uc?id=1NDc7jc9smkpEUVsBxl8LfHhJnw5PQ6mL",
  "https://drive.google.com/uc?id=1xUaFUwVM5dLT2c4ZKQCxOhR121GJ0aej",
  "https://drive.google.com/uc?id=13AsRBh2cHqYvMp5vtfniz10zzCD_M-2H",
  "https://drive.google.com/uc?id=122xAusguHEMG9R69wDLXm7C-MglyAVOv",
  "https://drive.google.com/uc?id=1VnmQewNkwhBJP2PT6beVFzi0q6jCjcZS",
  "https://drive.google.com/uc?id=1SXG5Y7IZs4Tf6a1BhqtoCfHe_8jMB0o2",
  "https://drive.google.com/uc?id=1wJoItaeK44mDRgbvDhXp7jSMtJEUSQl5",
  "https://drive.google.com/uc?id=1TTz9peuUnp0hf12lcCtVxPh8Nmw_s8NC",
  "https://drive.google.com/uc?id=1kZn4TgIWbnWHh4e24geHV5lkYQHfy3da",
  "https://drive.google.com/uc?id=1Xo4TeHwDUDq9jAo_eMsDU_4eqmN5AuRM",
  "https://drive.google.com/uc?id=1gwRDz-j5opeSOS9y6ful1wVBZhdlHien",
  "https://drive.google.com/uc?id=1f3DGXiVg9vplt14JycPXZmhuOW4a-ceA",
  "https://drive.google.com/uc?id=1tfyL0jlXs5lSq0agpzj-Q-nnjCJVUuhV",
  "https://drive.google.com/uc?id=10LGUyg53z_ClRuQwkenyeTWMF_FUl4g3",
  "https://drive.google.com/uc?id=1L5TX3PZh0PHgmMbWoAiRYNYCIUPqrFST",
  "https://drive.google.com/uc?id=1ANGgLCs_iI0YCIUwgEeGGSx9Fe1uRC5K",
  "https://drive.google.com/uc?id=1wcyGOuS6Ujlw0qnJPVfUfrF5qmi1Ycma",
  "https://drive.google.com/uc?id=187kVietMycfmILSF1sLerUFatDjDkWKC",
  "https://drive.google.com/uc?id=116pl9fVt-exCskisO8hAkr-A8sbiojrM",
  "https://drive.google.com/uc?id=1QftuYYPmrhmRCxa5wQqbctHHzJxA5a84",
  "https://drive.google.com/uc?id=1UEDGqV_f4f8Tt8F4lKJPXl3XPSdj6XFS",
  "https://drive.google.com/uc?id=1G4Owr3_x7IsQQx0VS96RsIm6ZrirqexP",
  "https://drive.google.com/uc?id=1cnJArBCk_Obcc97jMugPnK46wd6IrXUh",
  "https://drive.google.com/uc?id=1BiTRGhyyeG0g-mI_deuc4KxJfIckoUgu",
  "https://drive.google.com/uc?id=1bA6sxnjy4MsiQX0HY6MKF8c0s2yHcL20",
  "https://drive.google.com/uc?id=1d0v1iOmY6UMGBuvrNnG0j0D8xcLOg0VV",
  "https://drive.google.com/uc?id=1MdMezBbZRsE624HuR1NbNV77_UaW8hvh",
  "https://drive.google.com/uc?id=1KhR9jxjoSL1l8yDOtLE1dOEEOKSJciH8",
  "https://drive.google.com/uc?id=1CghgleV0o1XICTIzO3l50MrXxIguJdf2",
  "https://drive.google.com/uc?id=1GOhv-DXI5UIf2ZgnBXgZ0y_Hvr9llK5w",
  "https://drive.google.com/uc?id=1XG8qJTj0BX5brMLc5gkcialSBTzKHPhH",
  "https://drive.google.com/uc?id=1KCWgJmSPOfFUQUJQ2ehz_nKo6VLGnkiK",
  "https://drive.google.com/uc?id=1PnaIw_8MM12BpHbMnR5IqHM6qQwSHMeg",
  "https://drive.google.com/uc?id=1nigIEdbFzxYZP7wjKA9elKo70g5ts3ZK",
  "https://drive.google.com/uc?id=12uNEsT5Bv6sVcg9qz8NUn1hqEQRZ5A0n",
  "https://drive.google.com/uc?id=1yQ9ieXw_cvz9EfpAT3Hi5oXpaP5q4TaC",
  "https://drive.google.com/uc?id=1HTZQACZzfG-0x8jstL92IeGwrPuPQ_ej",
  "https://drive.google.com/uc?id=1kRH6xwWK_C-PgKT9PhH4GwkpKScbsqBW",
  "https://drive.google.com/uc?id=1Ulkrw0nJxm4erSzi1WlnS6FN5bzPp0z-",
  "https://drive.google.com/uc?id=1t1_Y_NMuMdPIVPpMpkf8tgC95Dv_O62G",
  "https://drive.google.com/uc?id=11tYU3Fo2mxUVytt-ahwjaZKAPGbuSIA4",
  "https://drive.google.com/uc?id=1t0il7PS8NYKkIysC-MQCRjnKfh_4A2ME",
  "https://drive.google.com/uc?id=1ig1x9y_mFbUSq01xR7zooRUDSxmMJ01s",
  "https://drive.google.com/uc?id=1Bp3GZujK6tv6ERX5Sx5pCApkczJuTTaF",
  "https://drive.google.com/uc?id=1_9Bdt2DKsMru_YpEzXVs1cErB5vKV3X5",
  "https://drive.google.com/uc?id=1H3qHU9Fh6CIQYH8vU_vO1pWsKlSlapN6",
  "https://drive.google.com/uc?id=12YgS9q5BN3nv4rIX-EXU6B_CsGBnyXMq",
  "https://drive.google.com/uc?id=1ffNTnAJrtb_QULVUCjJkTfOo3roQLrbc",
  "https://drive.google.com/uc?id=155CF_P3ODXPLKQ5JU-XkwlFgHsoRPVNV",
  "https://drive.google.com/uc?id=1b-CylajXF7PB0tSdSSQ9p5hgChY704P-",
  "https://drive.google.com/uc?id=12_57uSvYvf92andmRnVDLYhH6UROA8FV",
  "https://drive.google.com/uc?id=1X_9n0nBcPb6u6bMZxdmIp-k1wOOqJy9H",
  "https://drive.google.com/uc?id=10bwvC0jfyQlXXzHwLinz__bRhxo5SVR3",
  "https://drive.google.com/uc?id=1I2chnlDo5XGb_Luloyrvsq32OC9gvAEH",
  "https://drive.google.com/uc?id=1m9YbRMp-hOE2MTZU-nwHGE8wAQ8tBXQJ",
  "https://drive.google.com/uc?id=1D1bw1fCgb_KsxhAk5CkZ7UPdHaHcpBxm",
  "https://drive.google.com/uc?id=108buyAIuPdxxSt_bFX8lTqolN2rpWBUk",
  "https://drive.google.com/uc?id=16vw-FWMuy8o6Y4StM3MgnXEY1Dpo3jbS",
  "https://drive.google.com/uc?id=1thsHpGQvpg40-Y84uOBmzZpdEMBp7l2o",
  "https://drive.google.com/uc?id=1dHYsvzFxpp9fFuKP7JkDHnrX_y8XMwBa",
  "https://drive.google.com/uc?id=1cliSrg1ggJIJar4oFdnw2DJACB788JRl",
  "https://drive.google.com/uc?id=1hjKB4pnitBv6MsGixqtTuPjybYCxfNEI",
  "https://drive.google.com/uc?id=1u_Eq5OGZ0dYAQ7Cj6_qtzz_d6qyBJA0g",
  "https://drive.google.com/uc?id=1cSx8c1gF2-nT2ZDGSWK_PsrwikY-hyho",
  "https://drive.google.com/uc?id=1XwWQLg1aLhd9vdiGFX3J_JKsveiyHMkE",
  "https://drive.google.com/uc?id=1foDx1BAoNsTbpySfFgb0Tny8IMPFNX8n",
  "https://drive.google.com/uc?id=1xmONaIr8VSbUpeSBiMSr_JV8b0pzFWg8",
  "https://drive.google.com/uc?id=1hlfEs91deF2dXgZf1vw8Z9S0WnYIxg_M",
  "https://drive.google.com/uc?id=1J6MHOzSBKMAunIix9sYVNLCfnb0OgbUg",
  "https://drive.google.com/uc?id=1FgK908mBthXZkuDPPAwhsUhFnCqzk2uZ",
  "https://drive.google.com/uc?id=1VyuSif6QVux6aCFh6IV25ULCXfE_GNlL",
  "https://drive.google.com/uc?id=1jhiOhMPFcIWgBB11H_1515du3RT3Xaxc",
  "https://drive.google.com/uc?id=1n4YquSmSdjJOaSvAAFu48goWllvHb-YK",
  "https://drive.google.com/uc?id=1WR9D2E93gQczjjF50kfiRgVXWWWjJfdj",
  "https://drive.google.com/uc?id=10Bzjre74i6wKtCsKs5MtHf7zfgLPzVZy",
  "https://drive.google.com/uc?id=1dwodek9Zd0rmYmDBQvSg7lQzb7n5TX1i",
  "https://drive.google.com/uc?id=1s2w4rJ7TqvzPL5OeTedKEPj82KpnkInp",
  "https://drive.google.com/uc?id=17KKIRwS5hf7lvn_A0C8o0dC8yoG0Q7G_",
  "https://drive.google.com/uc?id=1TiGE4XaOYzg0p4cggq-6Yxn0_IysP0ch",
  "https://drive.google.com/uc?id=1UdTkBL-HyZ4T45iuSSjaxoKNe9fEzake",
  "https://drive.google.com/uc?id=1FLgqe1c_SkndQrBdl2YaqgOH0Np0l5Dt",
  "https://drive.google.com/uc?id=1L4hDxvH1i3s4I-pVxQuQPdbwbesVylM1",
  "https://drive.google.com/uc?id=1J4TJShcecoUVKySCLt_UO1nebsG7E0A-",
  "https://drive.google.com/uc?id=1m-DIhimSld5Eg4Ns601FTwso0SOexRnB",
  "https://drive.google.com/uc?id=1nzyPcuXBHhdglHp1Tdu4gfWjaBWXpFu2",
  "https://drive.google.com/uc?id=1fVohOF_S0KUPp9dNvap_I5blFGzl9345",
  "https://drive.google.com/uc?id=1nDA3PYGEz07t7zWEt2tyt-dYUum-Ls_G",
  "https://drive.google.com/uc?id=14XZ47MWYvgsp-NKTT3SGxS2wv7nYONov",
  "https://drive.google.com/uc?id=1txXA1Gwz_P_T_w5FKyfIVCXaFOwmX5UI",
  "https://drive.google.com/uc?id=1BY_tuYlZt-r3YkR7kUVkYLYY8nTznzLT",
  "https://drive.google.com/uc?id=1S8kZPKG9aMPJfmEj8w8O-pysUUz4yrk7",
  "https://drive.google.com/uc?id=1OuZmqsqKDlnMKMshYa8pE-1IsqdHsqf6",
  "https://drive.google.com/uc?id=1Y_P8i0daX3irz9p8vUanR_id0NgOn_vq",
  "https://drive.google.com/uc?id=1LGl2211jE0bMxYDtluTY1oQ_pN_h7yyf",
  "https://drive.google.com/uc?id=12OWVrM_hO-la0rpktO0XLyzWZCoKbm_D",
  "https://drive.google.com/uc?id=1xGDhozIF_V_JA3AG3_ae2ZQGsnGaKb20",
  "https://drive.google.com/uc?id=15E2642X3dUa3_qPWbu5dRCqllwmrgR30",
  "https://drive.google.com/uc?id=1DWcCpm-jHtFavgyTHVZSupuP7xLBnsqi",
  "https://drive.google.com/uc?id=1UPj0HDrQehFiGR6V7NVbCxJm7vhd8ufM",
  "https://drive.google.com/uc?id=1hpb2wrKPiX8EJPGA5rC63Hhh4EsYq7IF",
  "https://drive.google.com/uc?id=1lE_Of7qqRWxG-CSBr7Jlfli-6t941D4W",
  "https://drive.google.com/uc?id=1CvYriKoaEILcxdw7MhJqzjSkQNpbGWw8",
  "https://drive.google.com/uc?id=1D-mviOayx9Mq29TjpKMJoInzztxKROVy",
  "https://drive.google.com/uc?id=19ZzF0A0sZ-plhP5BZKakF8k9vdXtNOTe",
  "https://drive.google.com/uc?id=1W1jCN-lMhotivHe2grn02fTAVfP4-RGt",
  "https://drive.google.com/uc?id=1fhcCPHDhBtzNb55NdptUP5iBO_ZgBEiB",
  "https://drive.google.com/uc?id=1rf6f6OFPqiURDCksNHggxpA_A3Q2yMyQ",
  "https://drive.google.com/uc?id=1oRG6DH9ZPBgqkVYc12ztoR-DDr87yGVI",
  "https://drive.google.com/uc?id=1lENcXzMhH8UvgTc3q0CbsK96pvz8dDuE",
  "https://drive.google.com/uc?id=1nVzQ2q-zmHhx5Q01iTC5BU2rlUuuog8y",
  "https://drive.google.com/uc?id=1aijqvl2BnuVmt0pm2GS0KdgDeBfKaOER",
  "https://drive.google.com/uc?id=1ZHdN0on2oGBluKv5_qEs00nVb4ULWHJu",
  "https://drive.google.com/uc?id=1BAe-OfOnN74hOFc5Ssm06LibtWxK-_RO",
  "https://drive.google.com/uc?id=12sPI0u837gw82a-simOtwmUx0KgPab6b",
  "https://drive.google.com/uc?id=1rBBvZVeumxBE5z6MYLOx2G0H-6SEGov4",
  "https://drive.google.com/uc?id=1xKrGdE7VyfVoTvjOfjwB9b_jeP9gKMEm",
  "https://drive.google.com/uc?id=1jEirjciq3lZa8VZcAX4XhWSvOCcXRMEF",
  "https://drive.google.com/uc?id=1r3dMzt_PkicStQH1DmdU-ofLsS2nhJzJ",
  "https://drive.google.com/uc?id=18ZT3Wk-VDNPTCXPBO90N3kS6dV0_Ocs1",
  "https://drive.google.com/uc?id=1RQGKY-G9pfX2srFnzQd7TGTXWn5Y4KpJ",
  "https://drive.google.com/uc?id=1Bug9TQhh_0RZgaU9pcMNiNbZVppc_yzO",
  "https://drive.google.com/uc?id=1UockSxQsEUqMq_B49FpPfwN22bXV-Lp1",
  "https://drive.google.com/uc?id=1zTMqkE6M47M4caLlUe4k23s22xj2E8m5",
  "https://drive.google.com/uc?id=1-2pH3qZyB_dBGHuieau1X7WG1YrtUwiY",
  "https://drive.google.com/uc?id=1sHoe3fqA2yEeQV4auMzq9Xnv8-bBiIKj",
  "https://drive.google.com/uc?id=19tMJ9n-jItDlUFA63nV67v1krvMDaZxU",
  "https://drive.google.com/uc?id=1XeEUub2R1-8upKyrBQEXh0hCsTb2tunq",
  "https://drive.google.com/uc?id=1npOlujetFVS6HeyMWa2GlxA9jJ5K00QZ",
  "https://drive.google.com/uc?id=1qWhssEktMS7jVkhnihowrDthhsb9DZhl",
  "https://drive.google.com/uc?id=1CP1QeAnMqICBUBSl8b-kOTLHCc6Lwx-E",
  "https://drive.google.com/uc?id=1PfgJe4HnuUy7fNkPgoSILMipZdVv7bky",
  "https://drive.google.com/uc?id=1MulZZ25lzSLK-Jta9ihMgSZsnkoCZyz6",
  "https://drive.google.com/uc?id=1vTs3I8I7qywKsLuMBHVFtPA8GeMufr8R",
  "https://drive.google.com/uc?id=1hQGVLOFg0ckcHxMgbhO0PMO9rM2XzDwE",
  "https://drive.google.com/uc?id=15bmtcs7B9RO_kMbgKpdxnRxv6K_uXbZ8",
  "https://drive.google.com/uc?id=1bjJ7BTSNnihq6_Gh9OyBxVWyh1BO0As0",
  "https://drive.google.com/uc?id=1Ie1-2YogRW7NMqP7MHZgq2OLyW_x2q6u",
  "https://drive.google.com/uc?id=1TPtWK1AJ0LJRMXxdZce65GrDur6CH98q",
  "https://drive.google.com/uc?id=15nZS6oBImuFVfw7Lw5lk4T2KpYq1-uIp",
  "https://drive.google.com/uc?id=1FKqN0NT0XUwJYu_dkSdLgxz_j_RIeCx2",
  "https://drive.google.com/uc?id=11XxhjlUdqYn75wqYD53fb07sQYvLOTed",
  "https://drive.google.com/uc?id=1nz-njqWQCAiJAlv-3JWHYDMjeaC0vNZJ",
  "https://drive.google.com/uc?id=1YSv51HXIAHZ4WyhiM23JtCtLo6RrF0c5",
  "https://drive.google.com/uc?id=1lNggDaRcdii5SEDoFI8PcNqE02s-WQ63",
  "https://drive.google.com/uc?id=1N5B9cHOsl5HMYGa06CoWQhg7mgZPUUK9",
  "https://drive.google.com/uc?id=10sJJYbzk2qbcSPgglRt6-eJNqH6nxeGm",
  "https://drive.google.com/uc?id=1Bdq71BvXO_QXqQEowei8YtvAgyOzYNPk",
  "https://drive.google.com/uc?id=1vqt7UxU8ydx1Sn-HKv9LEleaMR1qlNX1",
  "https://drive.google.com/uc?id=1-7ZuRdenGV_E5tR0LzGvFX94CyN7HkWM",
  "https://drive.google.com/uc?id=1vdp_wPOhVpYwJO-39ZTbhYbWkUhssWqL",
  "https://drive.google.com/uc?id=1FXs9Rerg9ECPvqTM8YwGilxlkr140abe",
  "https://drive.google.com/uc?id=1PHNv0Vuykud6OYV46HKnVtsfhixRqHRk",
  "https://drive.google.com/uc?id=1R6InfPyCZXeZsi4ZAT32As_1IF9rtWAk",
  "https://drive.google.com/uc?id=1-JOew54IALJ2bJhhqoEFU7wjP_ZhqC5r",
  "https://drive.google.com/uc?id=1sahp7AWH8H9EA7nEYVvN2UlMj-OBIfqI",
  "https://drive.google.com/uc?id=1eHHquz98x9nD_hYC0o5gfjXZHpsYO5vG",
  "https://drive.google.com/uc?id=1iOmfVKrMylOQ9L9NnVxe3qTxuUqXENPb",
  "https://drive.google.com/uc?id=1bww9X8KMRWUSnZ0G8nJtww_aMxG4CeKR",
  "https://drive.google.com/uc?id=18GFqpV4orMuJkRrAtukt53jekFUpVMpc",
  "https://drive.google.com/uc?id=1kM82nvTh4NFtpVIlb3XCo5acd5hNJPyC",
  "https://drive.google.com/uc?id=1nLBQyx-cj6PooYfi6wTNc-4strz0nkdV",
  "https://drive.google.com/uc?id=1V8MhaNu0zHbRxH7LpS76iqNx_xClpZoJ",
  "https://drive.google.com/uc?id=1hUDxsbgOuCyd0HwnyonYOH_ik7JR9Uu_",
  "https://drive.google.com/uc?id=14bIM62aT8VUur3on71bQH-buuxeb-GvN",
  "https://drive.google.com/uc?id=1O5Q_RDT-oOgmn1EZM7M_b0_bGsQAImFQ",
  "https://drive.google.com/uc?id=12mfY5SI5K_mraMsFW6aCOrYXqourmWF2",
  "https://drive.google.com/uc?id=136wEU2oBEKonMzjvWNorwY8NJ-bwBkxy",
  "https://drive.google.com/uc?id=1U-4tyBOPoz_YjAWryRreGzndC_Ra_iIW",
  "https://drive.google.com/uc?id=1X7nr2QVY8XOs6Lq7ohtcMKGwfEBadkzt",
  "https://drive.google.com/uc?id=1mKvm-222z6H8ppmjXqG65Q3Llpe9_OF-",
  "https://drive.google.com/uc?id=1eI7YF8MiHI5fkPcDF6wR2PrwhoOu3-Hu",
  "https://drive.google.com/uc?id=1El95uQeUVSZFdYqZicjkahjCR4GKd-RK",
  "https://drive.google.com/uc?id=1kR9TJeBI6QEG1dhjjbfejrMkQiCjWXVQ",
  "https://drive.google.com/uc?id=1KZYAqzUDN-gvhBE9mj83-f5_x-US5nOg",
  "https://drive.google.com/uc?id=17RRoTVsKssODGNTH3aPVfuy_jC3t75ks",
  "https://drive.google.com/uc?id=1Sycm0q2Y4j5OL787QzzKP6vA7bNLa4zC",
  "https://drive.google.com/uc?id=1lmsNIngz0rrGV1fEDEOlzxWK47dHOQ_z",
  "https://drive.google.com/uc?id=11INtqN6ZiuWXtinh2PLuuwqmmNZxy_Km",
  "https://drive.google.com/uc?id=1YerZJQi5G9Wep4nwM3FSBeEbcilr7dPr",
  "https://drive.google.com/uc?id=1kTu_kUvGjq5UUgIQ0_HT6eDf_ymdcK2J",
  "https://drive.google.com/uc?id=188ZAmmco2YjGSISYPR5-IX6UnucI5FT-",
  "https://drive.google.com/uc?id=1axdKDHN7Mc4i7h4J3zIqLTtY2zGsxm6f",
  "https://drive.google.com/uc?id=1wrnKtAdtXQ_rRuRQu8AhtyaIOsIcpkOq",
  "https://drive.google.com/uc?id=1lStpOmk64NfrzF1-WOPdzDiO9wgHA-X_",
  "https://drive.google.com/uc?id=1BkfWBcwDJ0HxhAqw3tXASdaZJ9ZSq-5L",
  "https://drive.google.com/uc?id=1zRCsfFwyp-Sa4nz0ZHv9F8-Ar6GJXT8c",
  "https://drive.google.com/uc?id=1xhjr6B42GjK1pljUU9MnPd4Zts6DhsVh",
  "https://drive.google.com/uc?id=1NLJEjTgvwKUMV9SSPSGeTXA9L5L50ZQ1",
  "https://drive.google.com/uc?id=1sNvzdCsRD8ECh5N4oE6lLoBmdEc_6DA4",
  "https://drive.google.com/uc?id=1Nu9Qe7frXQ2iPazAtKceS1_zGSybxQCZ",
  "https://drive.google.com/uc?id=1jNwm2ntPFmcXpR-ED9d6YwwsQ5RZZa2H",
  "https://drive.google.com/uc?id=1-xZiagNYD6FsgDTisnn_VGUYbtvN8U5K",
  "https://drive.google.com/uc?id=1bIM3jbCg0r-hxlS9-0O36hK3gbFMyKtl",
  "https://drive.google.com/uc?id=1bJBPMyt5VGfDaC0ORy45oqZ-VIudkDMt",
  "https://drive.google.com/uc?id=1_Wg2tbfskSs6A8GNygJqGr146fUidlhx",
  "https://drive.google.com/uc?id=1jf9QpSvEoe-_S3RJqlA0nEl1cIadkkZi",
  "https://drive.google.com/uc?id=1vEvN-qZ_Yn3pTw5DpAQnQ2JTvJu57Pyn",
  "https://drive.google.com/uc?id=1YK3Vq5u981DQtsAlGA5-tRZrfw0-Gpew",
  "https://drive.google.com/uc?id=1Pas2FZ4aOgQBW9pSHUCFNDcOoRBxrYwU",
  "https://drive.google.com/uc?id=1cgBr1A5jvNzjx9CwRE92Wjlv00FpWEbK",
  "https://drive.google.com/uc?id=1C7fq_LPTMK6j6yMwqtJyqiYhXvjqkspG",
  "https://drive.google.com/uc?id=1JhJ8tMFdudg9934c9S-L0oHj695vteoq",
  "https://drive.google.com/uc?id=1I0EbANCCAodLWC3EprkhR0zMyJgU7kas",
  "https://drive.google.com/uc?id=1_6vBTrufXUK0ws74Bz5hO7bL4T39GUu6",
  "https://drive.google.com/uc?id=1cPBLeKl15R8cRakMyKRI_cKgCVITAAHh",
  "https://drive.google.com/uc?id=1hSehwymgLRFUBdSidSCgVGvIuwWhRv4B",
  "https://drive.google.com/uc?id=1jRndranwRHG8I6lb0luffGwGHU2S1J2-",
  "https://drive.google.com/uc?id=1uQ2G2gNqHvUIr3cFFpLJao-QsuFk_rwU",
  "https://drive.google.com/uc?id=17sc97mSB1JmNPOLbuqW-aqON6Xxwy4Gz",
  "https://drive.google.com/uc?id=1ql8lneoHllm2pPYQb5B8Lk46ThmlAkLR",
  "https://drive.google.com/uc?id=1Fj6jaaqdhV1Gv_dl6sF1sG_rl_b1ptwZ",
  "https://drive.google.com/uc?id=1u4-FIVCvXhNu9ClOvd9VfeTcIvWrvrZK",
  "https://drive.google.com/uc?id=1uwiCxwvHFQ3CDldgxNrlpUVJn7bNsPTO",
  "https://drive.google.com/uc?id=12kpnUM_EYLoaLDxb87OEHI2B0uWTsFNU",
  "https://drive.google.com/uc?id=1MBa329UCewGeLXGeLyTtPKY1pjYI7UyT",
  "https://drive.google.com/uc?id=1D70bDY7CkLtjW00_PxmJ5gokwXy3GPjN",
  "https://drive.google.com/uc?id=1KnBeliQkzZ-3oLx3bGzb6jAuN-WsFuJC",
  "https://drive.google.com/uc?id=1xgihnpO0Ru5jzEr_riGku6GIJ8cV4geD",
  "https://drive.google.com/uc?id=10VVpKJB5o5JH_xnd59tHrfDd4H0AP8QT",
  "https://drive.google.com/uc?id=1W9ivVAaxHYp6WSuMit8amsTTNp9C4vMO",
  "https://drive.google.com/uc?id=1z1d_ptR669Fu3gsDyIErmWvnzq4-XLBu",
  "https://drive.google.com/uc?id=10rvJ_bB-0EdTMRKiaSWqmvlxgV3gmOT6",
  "https://drive.google.com/uc?id=1aSGyHlEpj1UtJf-F8XE_3VTKty0OF62K",
  "https://drive.google.com/uc?id=1rKeVWArhO2PgFCuTgCcJ6BjkA4p1zIrg",
  "https://drive.google.com/uc?id=1Sd8Z7oc8zA0R-kRgCoAd7kaGcx_Chxkg",
  "https://drive.google.com/uc?id=1ejISOKEenguBiLAAnqfZfPXK0M7T623b",
  "https://drive.google.com/uc?id=1MIFfzLq8MHPiN2EfSaDxQmF9KnKmwKtt",
  "https://drive.google.com/uc?id=1sCPWJoPa7eHfsfqtGrhXKCFfYOkhECEq",
  "https://drive.google.com/uc?id=1dODP_sIhtx_SDflnWscnQjsRE1BPZB-T",
  "https://drive.google.com/uc?id=1JjuQdgYMUtE9pizlSnoLb8L_JiJ28uuH",
  "https://drive.google.com/uc?id=1ktyOCnK0iIke9RHZlO-UyvgRGX0ln8a7",
  "https://drive.google.com/uc?id=16SmnowTk-GUDGviSaxEuIW_XUba9sL3v",
  "https://drive.google.com/uc?id=1JJG4MrpbsvFdZPriOS12BxD8awNUbU8Z",
  "https://drive.google.com/uc?id=1vPlwEA722_C8aKhbbXrMpoLitRShFbbY",
  "https://drive.google.com/uc?id=1yN4WuD-cXR4NHqJkkJY0cQl_lUXocMTJ",
  "https://drive.google.com/uc?id=1gWNIxrU4_h-0kzfHAJ8oXR2nncpHEAm1",
  "https://drive.google.com/uc?id=19YPvRIeoknxEWHsgH9i7RlTCZe2-BGS3",
  "https://drive.google.com/uc?id=11e0KUq0cwMsuaIRL8eskPcV4izyBF6Sw",
  "https://drive.google.com/uc?id=1NFyHbAwvYM8fG0EP7onqxdGI9rFEyntz",
  "https://drive.google.com/uc?id=1kfECHzldGHmQJNEbpqRcfMc1PmEbF_02",
  "https://drive.google.com/uc?id=1yD_mv47IKqAnyBjaHyLWwl1-r6VQJuxy",
  "https://drive.google.com/uc?id=1_jp2qB-aXpFL67UyoPc_A2AflTYbMscR",
  "https://drive.google.com/uc?id=1Iz5JMo9jSgRJb_W_MogSS5yzSW2gkoDr",
  "https://drive.google.com/uc?id=1SGydtL8A2g7yL8h3432diy_NeDnfCpwS",
  "https://drive.google.com/uc?id=1CTeivVT7ZPZyJy08qmEPaXV6DFDD8ATh",
  "https://drive.google.com/uc?id=1Ti3p_xD5PB47qb5q6uIYwHsordHhU5Xn",
  "https://drive.google.com/uc?id=1eNUKdDdwcMpJQTflx-LcsuZrO3oELTdp",
  "https://drive.google.com/uc?id=11fDp1QjRRhkPYCx4cO1sYSIZN1mLO1hv",
  "https://drive.google.com/uc?id=1xPphCTUbHcXaOCJ78tIOtv8btg8LnFPO",
  "https://drive.google.com/uc?id=1CE1DpgRZP7YPXHZMxqDdZscmCu7ZCcDf",
  "https://drive.google.com/uc?id=1okFc1LvZXcAKYSIP_Yb8LCY7QOK8wvUh",
  "https://drive.google.com/uc?id=1kB1yBls8I6EcoY2895P-Rce_UAnCW8fT",
  "https://drive.google.com/uc?id=1hONalaj8xuUvpIT2VCyLJ27o_kLiSuun",
  "https://drive.google.com/uc?id=1_n-3bIYmC9B9x9j8w7k-pLEhlKtjHwUl",
  "https://drive.google.com/uc?id=1ltzr7Nu8Lq_DNJrdrUEWw0sKEFmCcVh0",
  "https://drive.google.com/uc?id=1x3HGcGsdk1YPYlH2sDm_ShY2QQIb-6OX",
  "https://drive.google.com/uc?id=1wErmdJH3zkwIipoCUx0m1m6E7zAr4bTZ",
  "https://drive.google.com/uc?id=19HJkiv_rHX9Ve2T33_EbMsW2EQyIzXdg",
  "https://drive.google.com/uc?id=1RLKqmYElwCJNcyVGOmRBZSMWDCE_-KDZ",
  "https://drive.google.com/uc?id=1RrY7nyArv4PUc1Y8WXeRUmEP4UnNP6xq",
  "https://drive.google.com/uc?id=1zW-0seh5HF95-cE6Bfn-QoOiqqJYGvqI",
  "https://drive.google.com/uc?id=1N3XuuLVikzXYfLZ3BOVj4F4bty9MyZ_T",
  "https://drive.google.com/uc?id=10boAOzqBpESGjIMweLf7sUmszxawrXXu",
  "https://drive.google.com/uc?id=1w4TxrZVs2JWTXoyAcTGvks1RZ3pAyQqW",
  "https://drive.google.com/uc?id=1v2RBW5pFreBsLHBjFZmRmgZ-40-dtR9P",
  "https://drive.google.com/uc?id=1lIIMWJNC8Wx2GECE-SVKr6I0l4Pq3U_B",
  "https://drive.google.com/uc?id=1EbmKBAKZ3h1PViJEBBUIXI_OKn-VV32D",
  "https://drive.google.com/uc?id=1N73AOks9euB4HUDlemQOmUah956FX2pj",
  "https://drive.google.com/uc?id=15w-cvMdMQAJiCwESLCJRtCVe6_2Gos1R",
  "https://drive.google.com/uc?id=1UHVSxbzuJV2PQI463eS02d6TwG4xPiDT",
  "https://drive.google.com/uc?id=1jDTrCghEGy4vmgg6AHkofQTirugwbXjp",
  "https://drive.google.com/uc?id=1eWGF8bz78-K-2cnD-wshCPB0pxEtZj_M",
  "https://drive.google.com/uc?id=1g-mjW8GMJxc-X15RgLKovrM_iZgHdaYF",
  "https://drive.google.com/uc?id=1p66tzrWVRXjvVwxuI0QS8MNhUcv3P_LL",
  "https://drive.google.com/uc?id=1yBh2KKWgN8iWjIPzr43oyDrubw9E5KiA",
  "https://drive.google.com/uc?id=1L_Dj8y5nIWSej6HP_LCp2cUGKsTiTbe3",
  "https://drive.google.com/uc?id=1vfDzqQEW0NcEhcjjG7hP89GFn0qmSajC",
  "https://drive.google.com/uc?id=18G0TQKXRXdvju90SuUKcCexah0_8JskL",
  "https://drive.google.com/uc?id=104QaIlU-o9Eya6-nxTyeVnGXxTjw-_Xf",
  "https://drive.google.com/uc?id=1DW5NUSu8Fap3Q3yYZN7sAFdK37i3rwU6",
];

const TOTAL_ITEMS = FILES.length;
const PER_PAGE = 50;
let INDEX = 0;

const loader = document.getElementById("loader");

async function Load() {
  loader.setAttribute("class", "loader-disabled");

  for (let index = 0; index < PER_PAGE; index++) {
    let grid_item = document.createElement("div");
    grid_item.setAttribute("class", "grid-item loading");
    grid.appendChild(grid_item);
  }

  for (let index = 0; index < PER_PAGE; index++) {
    let file = FILES[INDEX];
    let element = await Element(file);

    let loading = document.getElementsByClassName("loading")?.[0];
    if (loading) {
      loading.setAttribute("class", "grid-item");
      loading.appendChild(element);
    }
    INDEX++;
  }

  if (INDEX < TOTAL_ITEMS) {
    loader.setAttribute("class", "loader-enabled");
  } else {
    loader.setAttribute("class", "loader-disabled");
  }
}

function Element(file) {
  return new Promise((resolve) => {
    let img = new Image();
    img.src = file;
    img.onload = () => {
      resolve(img);
    };
    img.onerror = () => {
      let element = document.createElement("video");
      element.src = file;
      element.autoplay = true;
      element.muted = true;
      element.loop = true;
      element.onerror = () => {
        element?.parentNode?.parentNode?.removeChild(element.parentNode);
      };
      resolve(element);
    };
  });
}

window.onload = () => {
  loader.addEventListener("click", () => {
    Load();
  });
  Load();
};
